name: CI

on:
  push:
    branches:
      - master


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
        
      - name: Install all Go dependencies
        run: go get

      - name: go test
        run: go test